"""Predict IGR and emotion for congressional tweets using Claude API.

Reads the preprocessed eligible_tweets.csv (generated by prepare_data.py),
samples N tweets, calls Claude to predict in-group/out-group relationship
and emotion, then writes predictions.csv with results vs ground truth.

Usage:
    python3 claude_label/predict_igr.py [--sample-size 50] [--output predictions.csv] [--seed 42]
"""

import csv
import os
import json
import re
import random
import argparse
import time
import logging

from dotenv import load_dotenv
from anthropic import Anthropic

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
DATA_FILE = os.path.join(PROJECT_ROOT, "data", "eligible_tweets.csv")

load_dotenv(os.path.join(PROJECT_ROOT, ".env"))

logging.basicConfig(
    filename=os.path.join(SCRIPT_DIR, "prediction_errors.log"),
    level=logging.ERROR,
    format="%(asctime)s - %(message)s",
)


def load_eligible_tweets():
    """Read preprocessed eligible tweets from CSV."""
    tweets = []
    with open(DATA_FILE, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            tweets.append(row)
    return tweets


def parse_args():
    parser = argparse.ArgumentParser(
        description="Predict IGR and emotion for congressional tweets using Claude API"
    )
    parser.add_argument(
        "--sample-size", type=int, default=50,
        help="Number of tweets to sample (default: 50)"
    )
    parser.add_argument(
        "--output", type=str, default=os.path.join(SCRIPT_DIR, "predictions.csv"),
        help="Output CSV path (default: claude_label/predictions.csv)"
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Random seed for reproducibility (default: 42)"
    )
    return parser.parse_args()


def mask_handle(tweet_text, handle):
    """Replace all occurrences of the mentioned handle with @Doe (case-insensitive)."""
    masked = re.sub(re.escape(f"@{handle}"), "@Doe", tweet_text, flags=re.IGNORECASE)
    masked = re.sub(r'(?<!\w)' + re.escape(handle) + r'(?!\w)', "Doe", masked, flags=re.IGNORECASE)
    return masked


def predict_tweet(client, tweet_text, mentioned_handle):
    """Call Claude API to predict IGR and emotion for a tweet."""
    masked = mask_handle(tweet_text, mentioned_handle)

    prompt = f"""You are annotating tweets for a political communication research study.

Given this tweet, determine:
1. Interpersonal Group Relationship (IGR): Does the speaker appear to be talking about someone in their own group (In-Group) or a different group (Out-Group)? Base this only on linguistic cues, tone, and context.
2. Emotion toward @Doe: Choose exactly one from: Admiration, Anger, Disgust, Fear, Interest, Joy, Sadness, Surprise, No Emotion.

Tweet:
"{masked}"

Respond with ONLY this JSON, no other text:
{{"igr": "In-Group" or "Out-Group", "emotion": "<one emotion>", "reasoning": "<1-2 sentences>"}}"""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=256,
        temperature=0,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = message.content[0].text.strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)

    result = json.loads(raw)
    return {
        "igr": result["igr"],
        "emotion": result["emotion"],
        "reasoning": result.get("reasoning", ""),
    }


def run_predictions(sample):
    """Run Claude API predictions on sampled tweets with rate limiting."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set. Add it to .env or set as env var.")
        return []

    client = Anthropic(api_key=api_key)
    results = []
    errors = 0
    total = len(sample)

    for i, tweet in enumerate(sample):
        print(f"  [{i + 1}/{total}] Processing tweet {tweet['tweet_id']}...")

        try:
            prediction = predict_tweet(client, tweet["tweet_text"], tweet["mentioned_handle"])

            actual_igr = "In-Group" if tweet["tweeter_party"] == tweet["mentioned_party"] else "Out-Group"

            results.append({
                "tweet_id": tweet["tweet_id"],
                "tweeter_handle": tweet["tweeter_handle"],
                "mentioned_handle": tweet["mentioned_handle"],
                "tweet_text": tweet["tweet_text"],
                "predicted_igr": prediction["igr"],
                "predicted_emotion": prediction["emotion"],
                "actual_igr": actual_igr,
                "model_reasoning": prediction["reasoning"],
            })

        except Exception as e:
            errors += 1
            logging.error(f"Tweet {tweet['tweet_id']}: {type(e).__name__}: {e}")
            print(f"    ERROR: {e}")

        if i < total - 1:
            time.sleep(1.0)

    print(f"\n  Completed: {len(results)} successful, {errors} errors")
    return results


def write_csv(results, output_path):
    """Write prediction results to CSV."""
    fieldnames = [
        "tweet_id", "tweeter_handle", "mentioned_handle", "tweet_text",
        "predicted_igr", "predicted_emotion", "actual_igr", "model_reasoning",
    ]
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)


def print_summary(results):
    """Print accuracy summary stats."""
    if not results:
        return

    total = len(results)
    igr_correct = sum(1 for r in results if r["predicted_igr"] == r["actual_igr"])
    igr_accuracy = igr_correct / total * 100

    print(f"\n{'=' * 50}")
    print("SUMMARY")
    print(f"{'=' * 50}")
    print(f"Total predictions: {total}")
    print(f"IGR accuracy:      {igr_correct}/{total} ({igr_accuracy:.1f}%)")

    emotions = {}
    for r in results:
        e = r["predicted_emotion"]
        emotions[e] = emotions.get(e, 0) + 1

    print("\nEmotion distribution:")
    for emotion, count in sorted(emotions.items(), key=lambda x: -x[1]):
        print(f"  {emotion}: {count} ({count / total * 100:.1f}%)")

    in_group_pred = sum(1 for r in results if r["predicted_igr"] == "In-Group")
    out_group_pred = total - in_group_pred
    in_group_actual = sum(1 for r in results if r["actual_igr"] == "In-Group")
    out_group_actual = total - in_group_actual

    print("\nIGR breakdown:")
    print(f"  Predicted: {in_group_pred} In-Group, {out_group_pred} Out-Group")
    print(f"  Actual:    {in_group_actual} In-Group, {out_group_actual} Out-Group")
    print(f"{'=' * 50}")


if __name__ == "__main__":
    args = parse_args()

    print("Loading eligible tweets...")
    eligible = load_eligible_tweets()
    print(f"  Loaded {len(eligible)} eligible tweets")

    random.seed(args.seed)
    sample_size = min(args.sample_size, len(eligible))
    sample = random.sample(eligible, sample_size)
    print(f"  Sampled {sample_size} tweets (seed={args.seed})")

    print("\nRunning predictions...")
    results = run_predictions(sample)

    if results:
        write_csv(results, args.output)
        print(f"\nPredictions saved to {args.output}")
        print_summary(results)
    else:
        print("\nNo predictions generated. Check prediction_errors.log for details.")
